[workspace]
members = ["crates/cli", "crates/server"]

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["full"] }
actix-web = "4"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
