version: '3.3'

services:
  db:
    image: mysql
    container_name: mysql-container
    platform: linux/amd64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 888888
      MYSQL_DATABASE: db