name: Post to Alibaba Cloud
on:
  push:
    paths:
      - 'crates/server/**'

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install musl
        run: sudo apt-get install -y musl-tools

      - name: Build binary
        run: cargo build --verbose --release --package airnc-server
        env:
            RUST_BACKTRACE: 1

      - name: Post to Alibaba Cloud
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            ARGS: "-avz --delete"
            SOURCE: "target/release/airnc-server"
            TARGET: "${{ secrets.REMOTE_TARGET }}"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
